name: Push to Deta Space
on:
  push:
    branches:
      - master


jobs:
  push-to-space:
    runs-on: "ubuntu-20.04"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deta Space Deployment
        uses: neobrains/space-deployment-github-action@v0.5
        with:
          access_token: ${{ secrets.ACCESS_TOKEN }}
          project_id: ${{ secrets.PROJECT_ID }}
          space_push: true